import javax.swing.JFrame;


public class VentanaMicro extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMicro
     */
    public VentanaMicro() {
        initComponents();
        
        setMaximumSize(new java.awt.Dimension(700, 60));
        setPreferredSize(new java.awt.Dimension(700, 60));
         
        setVisible(true);
        setAlwaysOnTop(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBNHCm = new javax.swing.JButton();
        jBServiciom = new javax.swing.JButton();
        jBNombreDocm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(700, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 60));

        jBNHCm.setText("2.123.456");
        jBNHCm.setMaximumSize(new java.awt.Dimension(180, 60));
        jBNHCm.setMinimumSize(new java.awt.Dimension(180, 60));
        jBNHCm.setPreferredSize(new java.awt.Dimension(180, 60));
        jBNHCm.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N

        jBServiciom.setText("CAR");
        jBServiciom.setPreferredSize(new java.awt.Dimension(70, 60));
        jBServiciom.setMaximumSize(new java.awt.Dimension(70, 60));
        jBServiciom.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jBServiciom.setBackground(new java.awt.Color(233, 0, 0));

        jBNombreDocm.setText("jButton3");
        jBNombreDocm.setPreferredSize(new java.awt.Dimension(360, 60));
        jBNombreDocm.setMinimumSize(new java.awt.Dimension(360, 60));
        jBNombreDocm.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jBNHCm)
                //.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBServiciom)
                //.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBNombreDocm, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addComponent(jBNHCm)
            .addComponent(jBServiciom)
            .addComponent(jBNombreDocm)
        );

        /*
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1)
        );
        */
        
        getContentPane().add(jPanel1);

        pack();

    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMicro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMicro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMicro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMicro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMicro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    public javax.swing.JButton jBNHCm;
    public javax.swing.JButton jBNombreDocm;
    public javax.swing.JButton jBServiciom;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}

